trigger:
- main

pool:
  name: TestAgent

steps:
- script: mvnw.cmd clean test
  displayName: 'Run Maven Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'JUnit Test Results'